# .github/workflows/azure-static-web-apps-*.yml (Your generated file name)

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch: # Add this so you can run it manually

jobs:
  build_and_deploy_job:
    # Keep the 'if' condition if you only want it for pushes/PRs, remove if you only want manual trigger
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions: # Add permissions if not already present
      contents: read
    steps:
      - uses: actions/checkout@v4 # Use v4
        with:
          submodules: true
          # lfs: false # Usually not needed unless you use Git LFS

      # --- Added Build Steps ---
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Match your project's Node version

      - name: Install Root Dependencies
        run: npm install # Installs all monorepo dependencies

      - name: Build vinylplatz-web application
        run: npx nx build vinylplatz-web --configuration=production # Use Nx to build the specific frontend app
      # --- End of Added Build Steps ---

      - name: Deploy to Azure Static Web Apps # Changed step name for clarity
        id: builddeploy # Keep the original ID
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0FD759B03 }} # Use the secret Azure created
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Corrected Repository/Build Configurations ######
          app_location: "dist/apps/vinylplatz-web" # Correct: Path to the BUILT app output
          api_location: "" # Correct: API is hosted elsewhere
          output_location: "" # Correct: Not needed when action="upload" and app_location is the final output dir
          ###### End of Corrected Repository/Build Configurations ######

  # Keep the close_pull_request_job as Azure generated it
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0FD759B03 }}
          action: "close"
