# Name of the workflow displayed on GitHub Actions tab
name: Deploy VinylPlatz to GCP (Public SQL IP)

# Triggers: Run this workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

# Permissions required by the Google Cloud GitHub Actions
permissions:
  contents: 'read'   # Allows checking out the repository
  id-token: 'write'  # Allows authenticating to Google Cloud via OIDC/SA Key

# Environment variables available to all jobs/steps
env:
  NODE_VERSION: '20.x' # Specify Node.js version
  # Read secrets defined in GitHub repository settings
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ARTIFACT_REGISTRY_REPO: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}
  GCP_CLOUD_RUN_SERVICE_NAME: ${{ secrets.GCP_CLOUD_RUN_SERVICE_NAME }}
  GCP_CLOUD_RUN_REGION: ${{ secrets.GCP_CLOUD_RUN_REGION }}
  GCP_STORAGE_BUCKET_NAME: ${{ secrets.GCP_STORAGE_BUCKET_NAME }}
  # Consistent name for the Docker image being built/pushed
  BACKEND_IMAGE_NAME: vinylplatz-backend

# Define the jobs within the workflow
jobs:
  build_and_deploy:
    name: Build & Deploy to GCP # Name of the job
    runs-on: ubuntu-latest      # Use the latest Ubuntu runner provided by GitHub
    environment: production     # Optional: Link to a GitHub Environment

    steps:
    # --- Setup Steps ---
    - name: Checkout code
      uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Sets up the specified Node.js version
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm' # Enable caching for npm dependencies
        cache-dependency-path: /Users/miquelstam/vinylplatz/package-lock.json # Use absolute path for consistency

    - name: Install dependencies
      # Run npm ci from the workspace root. Use --force to potentially bypass peer dependency issues.
      run: npm ci --force
      working-directory: /Users/miquelstam/vinylplatz

    - name: Authenticate to Google Cloud
      id: auth # Give this step an ID to reference later if needed
      uses: 'google-github-actions/auth@v2' # Google's official action for authentication
      with:
        # Use the base64 encoded service account key stored as a secret
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK (gcloud)
      uses: 'google-github-actions/setup-gcloud@v2' # Installs and configures the gcloud CLI

    # --- Backend Build & Deploy (Cloud Run) ---
    - name: Configure Docker for Artifact Registry
      # Authenticates Docker CLI with Artifact Registry using gcloud credentials
      run: gcloud auth configure-docker ${{ env.GCP_ARTIFACT_REGISTRY_REPO.split('/')[0] }} --quiet

    - name: Set up Docker Buildx
      # Initializes Docker Buildx for enhanced build capabilities (like caching)
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Backend Docker Image
      id: docker_build # Give this step an ID to reference its outputs
      uses: docker/build-push-action@v5 # Action to build and push Docker images
      with:
        context: /Users/miquelstam/vinylplatz # Root of the workspace is the build context
        file: /Users/miquelstam/vinylplatz/apps/data-api/Dockerfile # Absolute path to the Dockerfile
        push: true # Push the built image to the registry
        # Tag the image with the full registry path and the unique commit SHA
        tags: ${{ env.GCP_ARTIFACT_REGISTRY_REPO }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha # Use GitHub Actions cache for Docker layers
        cache-to: type=gha,mode=max # Write cache layers back to GHA cache

    - name: Deploy Backend to Cloud Run
      id: deploy_backend # Give this step an ID to reference its outputs
      uses: 'google-github-actions/deploy-cloudrun@v2' # Action to deploy to Cloud Run
      with:
        service: ${{ env.GCP_CLOUD_RUN_SERVICE_NAME }} # Target Cloud Run service name
        region: ${{ env.GCP_CLOUD_RUN_REGION }}       # Target Cloud Run region
        # Use the immutable image digest output from the docker_build step
        image: ${{ steps.docker_build.outputs.digest }}
        # Pass runtime environment variables (read from GitHub Secrets)
        env_vars: |
          NODE_ENV=production
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          PORT=8080 # Standard port Cloud Run listens on

    # --- Frontend Build & Deploy (Cloud Storage) ---
    - name: Build Vue frontend
      # Run the Nx build command for the frontend app in production mode
      run: npx nx build vinylplatz-web --configuration=production
      working-directory: /Users/miquelstam/vinylplatz # Ensure command runs from workspace root
      env:
        # Critical: Set the VITE_API_URL environment variable during the build
        # This injects the *actual deployed backend URL* into the frontend code
        # Assumes your NestJS global prefix is /api. Adjust if different.
        VITE_API_URL: ${{ steps.deploy_backend.outputs.url }}/api

    - name: Deploy Frontend to Google Cloud Storage
      uses: 'google-github-actions/upload-cloud-storage@v2' # Action to upload files to GCS
      with:
        # Path to the built frontend artifacts within the runner's workspace
        path: /Users/miquelstam/vinylplatz/dist/apps/vinylplatz-web
        # Target GCS bucket (remove the 'gs://' prefix for the destination)
        destination: ${{ env.GCP_STORAGE_BUCKET_NAME.replace('gs://', '') }}
        # Upload contents directly into the bucket, not within a parent folder
        parent: false
        # Optional: Set cache headers for uploaded files
        headers: |
          cache-control: public, max-age=3600

