name: Build and deploy Node.js app to Azure Web App - vinylplatz-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # --- ADD THIS STEP ---
      - name: Reset Nx Cache
        run: npx nx reset

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Root Dependencies
        run: npm install

      - name: Build data-api application
        run: npx nx build data-api --configuration=production

      # --- Debugging: Add this step to see the directory structure ---
      # Helps confirm the build output path if errors persist
      - name: List directory structure after build
        run: ls -lR

      # --- Corrected Zipping Step ---
      # Change directory into the ACTUAL build output path defined by webpack.config.js
      # and zip its contents
      - name: Zip artifact for deployment
        run: |
          # Path based on apps/data-api/webpack.config.js output setting:
          cd apps/data-api/dist
          # Zip the contents of the dist folder. Adjust the relative path for the zip output:
          zip -r ../../../release.zip ./* ./.env* # Zip contents including hidden files like .env if present
          # Go back to the workspace root directory
          cd ../../..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app # Artifact name
          path: release.zip # Path to the zipped build output (at the repo root)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Use the same artifact name as uploaded

      # --- Deploy the ZIP directly, no unzip needed ---

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26CB6D6B18C24D1589557AE42CD8985D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C59C17796032408E863A825F7FF242AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66C8EAD4B38F49CBBFCCC3BC0C13BBF0 }}

      # --- Deploy the zipped artifact ---
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vinylplatz-api'
          slot-name: 'Production' # Consider using a staging slot first for safety
          package: release.zip # Deploy the ZIP file created in the build job
