# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vinylplatz-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Root Dependencies
        run: npm install # Installs all monorepo dependencies

      # --- Corrected Build Step ---
      - name: Build data-api application
        run: npx nx build data-api --configuration=production # Use Nx to build the specific app

      # --- Corrected Zipping Step ---
      # Change directory into the build output and zip its contents
      - name: Zip artifact for deployment
        run: |
          cd dist/apps/data-api
          zip -r ../../../release.zip ./* ./.env* # Zip contents including hidden files like .env if present
          cd ../../.. # Go back to the root directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app # Artifact name
          path: release.zip # Path to the zipped build output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Use the same artifact name

      # --- No need to Unzip ---
      # Remove the 'Unzip artifact for deployment' step

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26CB6D6B18C24D1589557AE42CD8985D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C59C17796032408E863A825F7FF242AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66C8EAD4B38F49CBBFCCC3BC0C13BBF0 }}

      # --- Corrected Deploy Step ---
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vinylplatz-api'
          slot-name: 'Production' # Consider using a staging slot first
          package: release.zip # Deploy the ZIP file directly
